spring:
  application:
    name: ai-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://localhost:3306/animal_management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "041115"
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3.5:4b
    openai:
      api-key: sk-ecc92b353a4741df8b5889c0bfbaacc8
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-v4-flash
          temperature: 0.3
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8085
